*                                                             
** SBClient Host 3GL API                                      
** Copyright (C) UniData, Inc., 1995                          
**      This software is the proprietary property and contains
**      trade secrets of UniData, Inc.  Any unauthorized use, 
**      disclosure or duplication is strictly prohibited.     
**      All rights reserved.                                  
*                                                             
READV CHECKTHERE FROM MDFL, FUNC, 1 THEN PRESENT = 1 ELSE PRESENT = 0
PRESENT = 1 ;!*UDT,UDTVMS,PI/O,PR1ME*!
