******************************************************************************
*
*   Header file for XML BASIC programs
*
*	Module	%M%	Version	%I% 	Date	%H%
*
*       (c) Copyright 2002 IBM Inc. - All Rights Reserved
*       This is unpublished proprietary source code of Ardent Software Inc.
*       The copyright notice above does not evidence any actual or intented
*       publication of such source code.
*
*******************************************************************************
*
*       Maintenence log - insert most recent change descriptions at top
*
*       Date.... GTAR# WHO Description.........................................
*
*****************************************************************************

* XML RETCODES and defines.

EQU XML.SUCCESS				TO		  0
EQU XML.ERROR				TO		 -1
EQU XML.INVALID.HANDLE			TO		 -2
EQU XML.EOF				TO		100


