*
** SBClient Host 3GL API
** Copyright (C) Ardent Software Inc. 1998
** Copyright (C) UniData, Inc. 1996, 1997
** Copyright (C) System Builder Corporation. 1995
**
**      This software is the proprietary property and contains
**      trade secrets of Ardent Software, Inc. Any unauthorized use,
**      disclosure or duplication is strictly prohibited.
**      All rights reserved.
*
READV CHECKTHERE FROM MDFL, FUNC, 1 THEN PRESENT = 1 ELSE PRESENT = 0
PRESENT = 1 ;!*UDT,UDTVMS,PI/O,PR1ME*!
