*
** SBClient Host 3GL API
** Copyright (C) Ardent Software Inc. 1998
** Copyright (C) UniData, Inc. 1996, 1997
** Copyright (C) System Builder Corporation. 1995
**
**      This software is the proprietary property and contains
**      trade secrets of Ardent Software, Inc. Any unauthorized use,
**      disclosure or duplication is strictly prohibited.
**      All rights reserved.
*
!@!TU.ITEM.ID = 'A':AM:0:AM:'ID':STR(AM, 6):'L':AM:10; !*PICK,AP,SEQ,ULT,ADDS,GA,ALTOS,MRX*!
TU.ITEM.ID = 'D':AM:0:AM:AM:'ID':AM:'10L':AM:'S';!*UV,UP,UDT,UDTVMS,PI/O,PR1ME*!
