* INCLUDE
*
** SBClient Host 3GL API
** Copyright (C) Ardent Software Inc. 1998
** Copyright (C) UniData, Inc. 1996, 1997
** Copyright (C) System Builder Corporation. 1995
**
**      This software is the proprietary property and contains
**      trade secrets of Ardent Software, Inc. Any unauthorized use,
**      disclosure or duplication is strictly prohibited.
**      All rights reserved.
*
EQU HED.DICTNAME TO 1
EQU HED.BORT TO 2
EQU HED.HEADING TO 3
EQU HED.JUST TO 4
EQU HED.LENGTH TO 5
EQU HED.OCONV TO 6
EQU HED.MASK TO 7
EQU HED.CONV TO 8
EQU HED.POSITION TO 9
*
EQU HED.HOSTFILENAME TO 11
EQU HED.FIELDLIST TO 12
EQU HED.SELECTION TO 13
EQU HED.IDCOUNT TO 14
EQU HED.RECORDCOUNT TO 15
EQU HED.XFERSIZE TO 16
