*
** SBClient Host 3GL API
** Copyright (C) Ardent Software Inc. 1998
** Copyright (C) UniData, Inc. 1996, 1997
** Copyright (C) System Builder Corporation. 1995
**
**      This software is the proprietary property and contains
**      trade secrets of Ardent Software, Inc. Any unauthorized use,
**      disclosure or duplication is strictly prohibited.
**      All rights reserved.
*
ID.TYPE = '@ID'                   ;!*UV,UP,PI/O,PR1ME,UDT,UDTVMS*!
!@!ID.TYPE = '*A0'; !*PICK,AP,SEQ,ULT,ALTOS,MRX,GA,ADDS*!
