*
** SBClient Host 3GL API
** Copyright (C) Ardent Software Inc. 1998
** Copyright (C) UniData, Inc. 1996, 1997
** Copyright (C) System Builder Corporation. 1995
**
**      This software is the proprietary property and contains
**      trade secrets of Ardent Software, Inc. Any unauthorized use,
**      disclosure or duplication is strictly prohibited.
**      All rights reserved.
*
*
*-* Include file for Scripting Engine
*
EQU SESSIONMASTER TO "sessionmaster"
EQU VBSCRIPT TO "vbscript"
EQU SCRIPT.ENGINE TO "SBClientScriptControl.VBScript"
EQU M.RESET TO "Reset"
EQU M.RUNCREATE TO "RunCreate"
EQU P.TIMEOUT TO "Timeout"
EQU P.USESAFESUBSET TO "UseSafeSubSet"
EQU P.LASTERROR TO "LastError"
EQU P.LISTMODULES TO "ListModules"
EQU M.ADDOBJECT TO "AddObject"
EQU M.CREATE.MODULE TO "CreateModule"
EQU M.EVAL TO "Eval"
EQU M.EXEC TO "ExecuteStatement"
EQU M.LIST.FUNCS TO "ListSubs"
EQU M.RUN TO "RunSub"
EQU M.ADDCODE TO "SendSub"
